print(bool(0))
print(bool(0.1))
print(bool("afsdafsd"))
ptint(bool("False"))

# print(int("fadsfasf"))
print(int("1"))
print(int(0.5))
print(int(False))
print(int(True))

print(float("1"))
print(float(0.5))
print(float(False))
print(float(True))